stream {
    upstream postgres_backend {
        server 127.0.0.1:5432;
    }

    server {
        # 'so_keepalive=on' configures TCP Keep-Alive on the client side
        # to prevent firewalls/NATs from dropping idle connections.
        listen 5433 ssl so_keepalive=on;

        proxy_pass postgres_backend;

        # Disable Nagle's algorithm to send packets immediately
        # (reduces latency for database queries)
        tcp_nodelay on;

        # Keep the connection to the PostgreSQL backend alive
        proxy_socket_keepalive on;

        # How long to wait to connect to the backend database
        proxy_connect_timeout 10s;

        # By default Nginx drops idle TCP streams after 10 minutes.
        # CI pipelines or long running queries may remain idle, so we increase this to 24 hours.
        proxy_timeout 24h;
        # Enable SSL and verify client
        ssl_certificate /etc/nginx/certs/postgres/server.crt;
        ssl_certificate_key /etc/nginx/certs/postgres/server.key;

        # Client Certificate Verification (The "password")
        ssl_client_certificate /etc/nginx/certs/postgres/ca.crt;
        ssl_verify_client on;
        ssl_verify_depth 2;
        # allow 1.2.3.4;
        # deny all;
    }
}
