# Unbound configuration file for Debian/Ubuntu.
#
# See the unbound.conf(5) man page.
#
# The following line includes additional configuration files from the
# /etc/unbound/unbound.conf.d directory.
include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"
